export const mtbFacebookPages = [
  'BiciAventuraCR',
  'multideportescr',
  'MTB-Rio-Pejivalle-513194345472172',
  'PakletearherediaMTByRuta',
  'RevistaBikecr',
  'wwwbikecrcom-159364380408',
  'crmtb',
  'ridegreenadventurescr',
  'ciclo.monociclo',
  'AcostaMTB',
  'ciclochavescr',
  'grupociclismorecreativo.hojancha',
  'SportClickGrecia',
  'promobikecr.net',
  'bicieventosmtb',
  'IRCRMTB',
  'AknaCRC'
];