export const FETCH_EVENTS_REQUEST = 'events/FETCH_EVENTS_REQUEST';
export const FETCH_EVENTS_SUCCESS = 'events/FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_FAILURE = 'events/FETCH_EVENTS_FAILURE';
export const FETCH_EVENTS_BATCH_SUCCESS = 'events/FETCH_EVENTS_BATCH_SUCCESS';
export const FETCH_EVENTS_DETAILS_SUCCESS = 'events/FETCH_EVENTS_DETAILS_SUCCESS';
